name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - run: yarn install
      - run: yarn build
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
#      - uses: actions/cache@v2
#        id: yarn-cache
#        with:
#          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-
#
#      - name: Installing dependencies
#        if: steps.yarn-cache.outputs.cache-hit != 'true'
#        run: |
#          echo "YARN CACHE CHANGED"
#          yarn install
#
#      - name: Build
#        run: yarn build


  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
        - run: yarn start
#      - name: CACHE ACTION
#        uses: actions/cache@v2
#        env:
#          cache-version: v1
#        id: yarn-cache
#        with:
#          path: |
#            ${{ steps.yarn-cache-dir-path.outputs.dir }}
#            **/node_modules
#          key: ${{ runner.os }}-yarn-${{ env.cache-version }}-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-${{ env.cache-version }}-
#            ${{ runner.os }}-yarn-
#            ${{ runner.os }}-

#      - name: Start server
#        run: yarn start

      - name: Start client
        run: yarn client

        env:
          CI: true
