name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set yarn global bin path
        run: |
          yarn config set prefix $(yarn cache dir)

      - name: Add yarn bin path to system path
        run: |
          echo $(yarn global bin) >> $GITHUB_PATH

      - name: Set yarn global installation path
        run: |
          yarn config set global-folder $(yarn cache dir)

      - name: CACHE ACTION
        uses: actions/cache@v2
        env:
          cache-version: v1
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ env.cache-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-version }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Installing dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          echo "YARN CACHE CHANGED"
          yarn install

      - name: Build
        run: yarn build
